### ISSUE TITLE
Hi, HP8770W+GTX970M can not use this OC ,Why ?  pls thank you very much

### ISSUE THREAD

**Issue by samhoor** [SkyrilHD/HP-8x70W-Hackintosh#30]
Hi, ，OpenCore 0.8.3 v7.0.2     After installing OpenCore Legacy Patcher, the screen is black and does not appear when restarting.
HP8770W+I7 3740qm+GTX970M+BCM94352HMB can not use this OC ,Why ?  pls thank you very much
Monterey and Big Sur all is no work,

**Comment by SkyrilHD** [comment]
This repo only supports GPUs that came with the 8x70W, meaning only Kepler and Chelsa. For Maxwell, you need to do custom patches. As far as I know, you can go up to High Sierra natively. However, there is some support for newer versions if you apply the OpenCore Legacy Patcher, though since there is no Metal support, you will be forced to use OpenCL which performs much worse in newer versions. I do not know exactly how to patch it, however I could give you at least some hints on how to get at least to macOS.

1. Remove Kepler/Chelsa device properties from the config. (Found in config.plist>DevicePropterties>PciRoot(0x0)/Pci(0x1,0x0)/Pci(0x0,0x0))
2. If enabled, disable SSDT-PNLF.aml from the config. (Found in config.plist>ACPI>Add>SSDT-PNLF.aml)

Now you should be able to boot to macOS without any acceleration. The next step would be to download and run OpenCore Legacy Patcher. In OCLP, try root-patching macOS to fix acceleration (and various issues).
